error: Uncaught exception   This is a simulated eroor  {"stack":"Error: This is a simulated eroor \n    at Object.<anonymous> (/home/sudeep/Documents/Web/Node.js Tutorial/vidly-project/index.js:65:11)\n    at Module._compile (node:internal/modules/cjs/loader:1241:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)\n    at Module.load (node:internal/modules/cjs/loader:1091:32)\n    at Module._load (node:internal/modules/cjs/loader:938:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47"}
error: Unhandled Rejection Occurred : unhaldled promise rejection 
error: Uncaught exception   This is a simulated eroor  {"stack":"Error: This is a simulated eroor \n    at Object.<anonymous> (/home/sudeep/Documents/Web/Node.js Tutorial/vidly-project/index.js:65:11)\n    at Module._compile (node:internal/modules/cjs/loader:1241:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)\n    at Module.load (node:internal/modules/cjs/loader:1091:32)\n    at Module._load (node:internal/modules/cjs/loader:938:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47"}
error: Uncaught execption This is an example of Uncaught exceptions ! 
error: Unhandled Rejection Occurred : unhaldled promise rejection 
